// <auto-generated />
using CorpusApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CorpusApi.Migrations
{
    [DbContext(typeof(CorpusApiContext))]
    [Migration("20191209221956_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CorpusApi.Models.Corpus", b =>
                {
                    b.Property<int>("CorpusId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Summary");

                    b.HasKey("CorpusId");

                    b.ToTable("CorpusApi");

                    b.HasData(
                        new
                        {
                            CorpusId = 1,
                            Summary = "This is a summary"
                        },
                        new
                        {
                            CorpusId = 2,
                            Summary = "This is another summary"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
